general.import = [ "~/.config/omarchy/current/theme/alacritty.toml" ]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "MesloLGL Nerd Font" }
bold = { family = "MesloLGL Nerd Font" }
italic = { family = "MesloLGL Nerd Font" }
size = 15

[terminal.shell]
program = "/usr/bin/zsh"

[window]
padding.x = 14
padding.y = 14
decorations = "None"
opacity = 0.5
blur = false

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" },
{ key = "Insert", mods = "Shift", action = "Paste" },
{ key = "Insert", mods = "Control", action = "Copy" }
]

[cursor]
style = { shape = "Beam", blinking = "Off"}
